remote_theme: pages-themes/slate@v0.2.0
title: Zhen's homepage
description: Bookmark this to keep an eye on my project updates!
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
